# Generated by Django 5.2.1 on 2025-05-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealdistribution',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
