# Generated by Django 5.2.1 on 2025-05-30 00:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('prepared_portions', models.PositiveIntegerField(default=0)),
                ('possible_portions', models.PositiveIntegerField(default=0)),
                ('difference_percent', models.FloatField(default=0.0)),
                ('warning', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-report_date'],
                'unique_together': {('report_date',)},
            },
        ),
    ]
